compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  react-avatar-editor@^13.0.0:
    peerDependencies:
      "@babel/core": ^7.0.0

yarnPath: .yarn/releases/yarn-4.0.0.cjs
